function [fitresult, gof, max_acc,id_acc] = createFit(a, b)
%CREATEFIT(A,B)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : a
%      Y Output: b
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
%  max_acc : maximum propulsion acceleration
%  Auto-generated by MATLAB on 02-Nov-2016 21:21:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( a, b );


% Set up fittype and options.
ft = fittype( 'poly7' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
    close all;
    figure( 'Name', 'Fit' );
    hold on
    h = plot( fitresult, xData, yData );

d = differentiate(fitresult,xData);
figure; plot(d)

[peaks,ids]=findpeaks(d);
[max_acc,id]=max(peaks);
id_acc=ids(id);

% plot(xData,differentiate(fitresult,xData))

% grid on


